spring:
  application:
    name: IntelligentChatbot
  ai:
    openai:
      #OpenAI
#      api-key: sk-proj-XXXXX
      #DeepSeek
      api-key: sk-9e343ee51d48468c889e347c9d8a3044
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'
    file: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'
  level:
    org.springframework.ai.chat.client.advisor: debug
